In [1]:
from ephys_behavior import get_qc_passed_units_metadata_combined
from general_utils import smart_read_csv, find_ephys_sessions
sessions = find_ephys_sessions()
get_qc_passed_units_metadata_combined(session_names=sessions[2],save_result=True)

Processing QC metadata for 41 sessions...

[1/41] Loading session ecephys_753124_2024-12-10_17-24-56_sorted_2024-12-13_09-48-25 ...
Found ephys NWB: /root/capsule/data/ecephys_753124_2024-12-10_17-24-56_sorted_2024-12-13_09-48-25/nwb/ecephys_753124_2024-12-10_17-24-56_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_753124_2024-12-10_17-24-56_sorted_2024-12-13_09-48-25/nwb/ecephys_753124_2024-12-10_17-24-56_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/753124_2024-12-10_17-24-56.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/753124_2024-12-10_17-24-56.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 528
  → Found 528 QC-passed units.

[2/41] Loading session ecephys_753125_2024-10-09_10-50-19_sorted_2024-11-09_20-03-58 ...
Found ephys NWB: /root/capsule/data/ecephys_753125_2024-10-09_10-50-19_sorted_2024-11-09_20-03-58/nwb/ecephys_753125_2024-10-09_10-50-19_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_753125_2024-10-09_10-50-19_sorted_2024-11-09_20-03-58/nwb/ecephys_753125_2024-10-09_10-50-19_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/753125_2024-10-09_10-50-19.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/753125_2024-10-09_10-50-19.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 248
  → Found 248 QC-passed units.

[3/41] Loading session ecephys_753125_2024-10-10_14-41-23_sorted_2024-11-09_20-18-36 ...
Found ephys NWB: /root/capsule/data/ecephys_753125_2024-10-10_14-41-23_sorted_2024-11-09_20-18-36/nwb/ecephys_753125_2024-10-10_14-41-23_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_753125_2024-10-10_14-41-23_sorted_2024-11-09_20-18-36/nwb/ecephys_753125_2024-10-10_14-41-23_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/753125_2024-10-10_14-41-23.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/753125_2024-10-10_14-41-23.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 62
  → Found 62 QC-passed units.

[4/41] Loading session ecephys_753125_2024-10-14_15-37-15_sorted_2024-11-09_20-07-38 ...
Found ephys NWB: /root/capsule/data/ecephys_753125_2024-10-14_15-37-15_sorted_2024-11-09_20-07-38/nwb/ecephys_753125_2024-10-14_15-37-15_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_753125_2024-10-14_15-37-15_sorted_2024-11-09_20-07-38/nwb/ecephys_753125_2024-10-14_15-37-15_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/753125_2024-10-14_15-37-15.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/753125_2024-10-14_15-37-15.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 274
  → Found 274 QC-passed units.

[5/41] Loading session ecephys_753125_2024-10-15_16-16-22_sorted_2024-11-09_19-57-50 ...
Found ephys NWB: /root/capsule/data/ecephys_753125_2024-10-15_16-16-22_sorted_2024-11-09_19-57-50/nwb/ecephys_753125_2024-10-15_16-16-22_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_753125_2024-10-15_16-16-22_sorted_2024-11-09_19-57-50/nwb/ecephys_753125_2024-10-15_16-16-22_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/753125_2024-10-15_16-16-22.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/753125_2024-10-15_16-16-22.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 239
  → Found 239 QC-passed units.

[6/41] Loading session ecephys_753126_2024-10-10_17-51-24_sorted_2025-02-21_13-56-40 ...
Found ephys NWB: /root/capsule/data/ecephys_753126_2024-10-10_17-51-24_sorted_2025-02-21_13-56-40/nwb/ecephys_753126_2024-10-10_17-51-24_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_753126_2024-10-10_17-51-24_sorted_2025-02-21_13-56-40/nwb/ecephys_753126_2024-10-10_17-51-24_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/753126_2024-10-10_17-51-24.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/753126_2024-10-10_17-51-24.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 520
  → Found 520 QC-passed units.

[7/41] Loading session ecephys_753126_2024-10-11_13-14-24_sorted_2024-11-09_19-18-21 ...
Found ephys NWB: /root/capsule/data/ecephys_753126_2024-10-11_13-14-24_sorted_2024-11-09_19-18-21/nwb/ecephys_753126_2024-10-11_13-14-24_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_753126_2024-10-11_13-14-24_sorted_2024-11-09_19-18-21/nwb/ecephys_753126_2024-10-11_13-14-24_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/753126_2024-10-11_13-14-24.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/753126_2024-10-11_13-14-24.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 383
  → Found 383 QC-passed units.

[8/41] Loading session ecephys_753126_2024-10-15_12-20-35_sorted_2024-11-09_19-47-57 ...
Found ephys NWB: /root/capsule/data/ecephys_753126_2024-10-15_12-20-35_sorted_2024-11-09_19-47-57/nwb/ecephys_753126_2024-10-15_12-20-35_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_753126_2024-10-15_12-20-35_sorted_2024-11-09_19-47-57/nwb/ecephys_753126_2024-10-15_12-20-35_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/753126_2024-10-15_12-20-35.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/753126_2024-10-15_12-20-35.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 359
  → Found 359 QC-passed units.

[9/41] Loading session ecephys_764769_2024-12-11_18-21-49_sorted_2024-12-13_10-04-48 ...
Found ephys NWB: /root/capsule/data/ecephys_764769_2024-12-11_18-21-49_sorted_2024-12-13_10-04-48/nwb/ecephys_764769_2024-12-11_18-21-49_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764769_2024-12-11_18-21-49_sorted_2024-12-13_10-04-48/nwb/ecephys_764769_2024-12-11_18-21-49_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/behavior_764769_2024-12-11_18-21-49.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/behavior_764769_2024-12-11_18-21-49.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 670
  → Found 670 QC-passed units.

[10/41] Loading session ecephys_764769_2024-12-12_16-05-00_sorted_2024-12-13_10-34-23 ...
Found ephys NWB: /root/capsule/data/ecephys_764769_2024-12-12_16-05-00_sorted_2024-12-13_10-34-23/nwb/ecephys_764769_2024-12-12_16-05-00_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764769_2024-12-12_16-05-00_sorted_2024-12-13_10-34-23/nwb/ecephys_764769_2024-12-12_16-05-00_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/behavior_764769_2024-12-12_16-05-00.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/behavior_764769_2024-12-12_16-05-00.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 463
  → Found 463 QC-passed units.

[11/41] Loading session ecephys_764769_2024-12-13_15-41-07_sorted_2024-12-17_18-00-23 ...
Found ephys NWB: /root/capsule/data/ecephys_764769_2024-12-13_15-41-07_sorted_2024-12-17_18-00-23/nwb/ecephys_764769_2024-12-13_15-41-07_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764769_2024-12-13_15-41-07_sorted_2024-12-17_18-00-23/nwb/ecephys_764769_2024-12-13_15-41-07_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/behavior_764769_2024-12-13_15-41-07.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/behavior_764769_2024-12-13_15-41-07.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 608
  → Found 608 QC-passed units.

[12/41] Loading session ecephys_764787_2024-12-10_13-42-03_sorted_2025-01-24_15-52-45 ...
Warning: No NWB file found with pattern '/root/capsule/data/ecephys_764787_2024-12-10_13-42-03_sorted_2025-01-24_15-52-45/nwb/*experiment1_recording1.nwb'.
Found behavior NWB: /root/capsule/data/behavior_nwb/764787_2024-12-10_13-42-03.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/764787_2024-12-10_13-42-03.nwb
Warning: Ephys NWB failed to load; returning behavior NWB only.
  → Warning: tag='behavior_only' – no ephys for session ecephys_764787_2024-12-10_13-42-03_sorted_2025-01-24_15-52-45, skipping.

[13/41] Loading session ecephys_764787_2024-12-11_15-01-15_sorted_2025-02-21_17-11-57 ...
Found ephys NWB: /root/capsule/data/ecephys_764787_2024-12-11_15-01-15_sorted_2025-02-21_17-11-57/nwb/ecephys_764787_2024-12-11_15-01-15_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764787_2024-12-11_15-01-15_sorted_2025-02-21_17-11-57/nwb/ecephys_764787_2024-12-11_15-01-15_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/behavior_764787_2024-12-11_15-01-15.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/behavior_764787_2024-12-11_15-01-15.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 530
  → Found 530 QC-passed units.

[14/41] Loading session ecephys_764787_2024-12-12_11-54-14_sorted_2024-12-13_10-39-18 ...
Found ephys NWB: /root/capsule/data/ecephys_764787_2024-12-12_11-54-14_sorted_2024-12-13_10-39-18/nwb/ecephys_764787_2024-12-12_11-54-14_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764787_2024-12-12_11-54-14_sorted_2024-12-13_10-39-18/nwb/ecephys_764787_2024-12-12_11-54-14_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/behavior_764787_2024-12-12_11-54-14.nwb

/opt/conda/lib/python3.10/site-packages/hdmf/spec/namespace.py:583: UserWarning: Ignoring the following cached namespace(s) because another version is already loaded:
core - cached version: 2.6.0-alpha, loaded version: 2.7.0
The loaded extension(s) may not be compatible with the cached extension(s) in the file. Please check the extension documentation and ignore this warning if these versions are compatible.
  self.warn_for_ignored_namespaces(ignored_namespaces)

Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/behavior_764787_2024-12-12_11-54-14.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 810
  → Found 810 QC-passed units.

[15/41] Loading session ecephys_764787_2024-12-13_18-27-42_sorted_2024-12-17_18-31-24 ...
Found ephys NWB: /root/capsule/data/ecephys_764787_2024-12-13_18-27-42_sorted_2024-12-17_18-31-24/nwb/ecephys_764787_2024-12-13_18-27-42_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764787_2024-12-13_18-27-42_sorted_2024-12-17_18-31-24/nwb/ecephys_764787_2024-12-13_18-27-42_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/behavior_764787_2024-12-13_18-27-42.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/behavior_764787_2024-12-13_18-27-42.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 150
  → Found 150 QC-passed units.

[16/41] Loading session ecephys_764790_2024-12-17_16-57-52_sorted_2024-12-20_18-46-41 ...
Found ephys NWB: /root/capsule/data/ecephys_764790_2024-12-17_16-57-52_sorted_2024-12-20_18-46-41/nwb/ecephys_764790_2024-12-17_16-57-52_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764790_2024-12-17_16-57-52_sorted_2024-12-20_18-46-41/nwb/ecephys_764790_2024-12-17_16-57-52_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/behavior_764790_2024-12-17_16-57-52.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/behavior_764790_2024-12-17_16-57-52.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 582
  → Found 582 QC-passed units.

[17/41] Loading session ecephys_764790_2024-12-18_12-14-41_sorted_2024-12-21_23-37-20 ...
Found ephys NWB: /root/capsule/data/ecephys_764790_2024-12-18_12-14-41_sorted_2024-12-21_23-37-20/nwb/ecephys_764790_2024-12-18_12-14-41_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764790_2024-12-18_12-14-41_sorted_2024-12-21_23-37-20/nwb/ecephys_764790_2024-12-18_12-14-41_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/764790_2024-12-18_12-14-41.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/764790_2024-12-18_12-14-41.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 334
  → Found 334 QC-passed units.

[18/41] Loading session ecephys_764790_2024-12-19_16-11-34_sorted_2025-02-21_14-46-33 ...
Found ephys NWB: /root/capsule/data/ecephys_764790_2024-12-19_16-11-34_sorted_2025-02-21_14-46-33/nwb/ecephys_764790_2024-12-19_16-11-34_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764790_2024-12-19_16-11-34_sorted_2025-02-21_14-46-33/nwb/ecephys_764790_2024-12-19_16-11-34_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/764790_2024-12-19_16-11-34.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/764790_2024-12-19_16-11-34.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 514
  → Found 514 QC-passed units.

[19/41] Loading session ecephys_764790_2024-12-20_16-56-37_sorted_2024-12-22_00-06-37 ...
Found ephys NWB: /root/capsule/data/ecephys_764790_2024-12-20_16-56-37_sorted_2024-12-22_00-06-37/nwb/ecephys_764790_2024-12-20_16-56-37_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764790_2024-12-20_16-56-37_sorted_2024-12-22_00-06-37/nwb/ecephys_764790_2024-12-20_16-56-37_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/764790_2024-12-20_16-56-37.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/764790_2024-12-20_16-56-37.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 597
  → Found 597 QC-passed units.

[20/41] Loading session ecephys_764791_2025-01-14_12-04-05_sorted_2025-04-24_18-24-08 ...
Found ephys NWB: /root/capsule/data/ecephys_764791_2025-01-14_12-04-05_sorted_2025-04-24_18-24-08/nwb/ecephys_764791_2025-01-14_12-04-05_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764791_2025-01-14_12-04-05_sorted_2025-04-24_18-24-08/nwb/ecephys_764791_2025-01-14_12-04-05_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/764791_2025-01-14_12-04-05.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/764791_2025-01-14_12-04-05.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 297
  → Found 297 QC-passed units.

[21/41] Loading session ecephys_764791_2025-01-15_13-08-58_sorted_2025-01-16_11-46-50 ...
Found ephys NWB: /root/capsule/data/ecephys_764791_2025-01-15_13-08-58_sorted_2025-01-16_11-46-50/nwb/ecephys_764791_2025-01-15_13-08-58_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764791_2025-01-15_13-08-58_sorted_2025-01-16_11-46-50/nwb/ecephys_764791_2025-01-15_13-08-58_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/764791_2025-01-15_13-08-58.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/764791_2025-01-15_13-08-58.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
  → ERROR while processing session ecephys_764791_2025-01-15_13-08-58_sorted_2025-01-16_11-46-50: 'waveform_mean'. Skipping this session.

[22/41] Loading session ecephys_764791_2025-01-16_12-50-17_sorted_2025-04-25_14-11-37 ...
Found ephys NWB: /root/capsule/data/ecephys_764791_2025-01-16_12-50-17_sorted_2025-04-25_14-11-37/nwb/ecephys_764791_2025-01-16_12-50-17_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_764791_2025-01-16_12-50-17_sorted_2025-04-25_14-11-37/nwb/ecephys_764791_2025-01-16_12-50-17_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/764791_2025-01-16_12-50-17.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/764791_2025-01-16_12-50-17.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 525
  → Found 525 QC-passed units.

[23/41] Loading session ecephys_769882_2025-01-28_19-07-31_sorted_2025-01-29_04-56-02 ...
Found ephys NWB: /root/capsule/data/ecephys_769882_2025-01-28_19-07-31_sorted_2025-01-29_04-56-02/nwb/ecephys_769882_2025-01-28_19-07-31_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_769882_2025-01-28_19-07-31_sorted_2025-01-29_04-56-02/nwb/ecephys_769882_2025-01-28_19-07-31_experiment1_recording1.nwb
Warning: No behavior NWB files found for session '769882_2025-01-28_19-07-31' under ['/root/capsule/data/behavior_nwb', '/root/capsule/data/optogenetics_nwb'].
Warning: Behavior NWB failed to load; returning ephys NWB only.
  → Extracting QC-passed units metadata...
Number of units passing QC: 152
  → Found 152 QC-passed units.

[24/41] Loading session ecephys_769884_2025-01-14_14-53-24_sorted_2025-01-24_14-20-13 ...
Found ephys NWB: /root/capsule/data/ecephys_769884_2025-01-14_14-53-24_sorted_2025-01-24_14-20-13/nwb/ecephys_769884_2025-01-14_14-53-24_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_769884_2025-01-14_14-53-24_sorted_2025-01-24_14-20-13/nwb/ecephys_769884_2025-01-14_14-53-24_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/769884_2025-01-14_14-53-24.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/769884_2025-01-14_14-53-24.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 289
  → Found 289 QC-passed units.

[25/41] Loading session ecephys_769884_2025-01-15_16-12-59_sorted_2025-04-24_17-11-57 ...
Found ephys NWB: /root/capsule/data/ecephys_769884_2025-01-15_16-12-59_sorted_2025-04-24_17-11-57/nwb/ecephys_769884_2025-01-15_16-12-59_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_769884_2025-01-15_16-12-59_sorted_2025-04-24_17-11-57/nwb/ecephys_769884_2025-01-15_16-12-59_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/769884_2025-01-15_16-12-59.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/769884_2025-01-15_16-12-59.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 695
  → Found 695 QC-passed units.

[26/41] Loading session ecephys_769884_2025-01-16_18-33-11_sorted_2025-04-24_19-24-23 ...
Found ephys NWB: /root/capsule/data/ecephys_769884_2025-01-16_18-33-11_sorted_2025-04-24_19-24-23/nwb/ecephys_769884_2025-01-16_18-33-11_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_769884_2025-01-16_18-33-11_sorted_2025-04-24_19-24-23/nwb/ecephys_769884_2025-01-16_18-33-11_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/769884_2025-01-16_18-33-11.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/769884_2025-01-16_18-33-11.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 322
  → Found 322 QC-passed units.

[27/41] Loading session ecephys_776293_2025-02-14_15-19-17_sorted_2025-02-28_21-37-07 ...
Found ephys NWB: /root/capsule/data/ecephys_776293_2025-02-14_15-19-17_sorted_2025-02-28_21-37-07/nwb/ecephys_776293_2025-02-14_15-19-17_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_776293_2025-02-14_15-19-17_sorted_2025-02-28_21-37-07/nwb/ecephys_776293_2025-02-14_15-19-17_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/776293_2025-02-14_15-19-17.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/776293_2025-02-14_15-19-17.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 800
  → Found 800 QC-passed units.

[28/41] Loading session ecephys_776293_2025-02-18_12-51-36_sorted_2025-03-30_05-50-33 ...
Found ephys NWB: /root/capsule/data/ecephys_776293_2025-02-18_12-51-36_sorted_2025-03-30_05-50-33/nwb/ecephys_776293_2025-02-18_12-51-36_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_776293_2025-02-18_12-51-36_sorted_2025-03-30_05-50-33/nwb/ecephys_776293_2025-02-18_12-51-36_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/776293_2025-02-18_12-51-36.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/776293_2025-02-18_12-51-36.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 1168
  → Found 1168 QC-passed units.

[29/41] Loading session ecephys_776293_2025-02-19_14-01-07_sorted_2025-03-30_08-55-28 ...
Found ephys NWB: /root/capsule/data/ecephys_776293_2025-02-19_14-01-07_sorted_2025-03-30_08-55-28/nwb/ecephys_776293_2025-02-19_14-01-07_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_776293_2025-02-19_14-01-07_sorted_2025-03-30_08-55-28/nwb/ecephys_776293_2025-02-19_14-01-07_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/776293_2025-02-19_14-01-07.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/776293_2025-02-19_14-01-07.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 1295
  → Found 1295 QC-passed units.

[30/41] Loading session ecephys_776293_2025-02-20_14-03-10_sorted_2025-03-30_03-39-17 ...
Found ephys NWB: /root/capsule/data/ecephys_776293_2025-02-20_14-03-10_sorted_2025-03-30_03-39-17/nwb/ecephys_776293_2025-02-20_14-03-10_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_776293_2025-02-20_14-03-10_sorted_2025-03-30_03-39-17/nwb/ecephys_776293_2025-02-20_14-03-10_experiment1_recording1.nwb
Warning: No behavior NWB files found for session '776293_2025-02-20_14-03-10' under ['/root/capsule/data/behavior_nwb', '/root/capsule/data/optogenetics_nwb'].
Warning: Behavior NWB failed to load; returning ephys NWB only.
  → Extracting QC-passed units metadata...
Number of units passing QC: 955
  → Found 955 QC-passed units.

[31/41] Loading session ecephys_780618_2025-04-15_13-30-58_sorted_2025-04-18_12-52-04 ...
Found ephys NWB: /root/capsule/data/ecephys_780618_2025-04-15_13-30-58_sorted_2025-04-18_12-52-04/nwb/ecephys_780618_2025-04-15_13-30-58_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_780618_2025-04-15_13-30-58_sorted_2025-04-18_12-52-04/nwb/ecephys_780618_2025-04-15_13-30-58_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/780618_2025-04-15_13-30-58.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/780618_2025-04-15_13-30-58.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 660
  → Found 660 QC-passed units.

[32/41] Loading session ecephys_780618_2025-04-16_15-54-21_sorted_2025-04-18_12-51-23 ...
Found ephys NWB: /root/capsule/data/ecephys_780618_2025-04-16_15-54-21_sorted_2025-04-18_12-51-23/nwb/ecephys_780618_2025-04-16_15-54-21_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_780618_2025-04-16_15-54-21_sorted_2025-04-18_12-51-23/nwb/ecephys_780618_2025-04-16_15-54-21_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/780618_2025-04-16_15-54-21.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/780618_2025-04-16_15-54-21.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 1290
  → Found 1290 QC-passed units.

[33/41] Loading session ecephys_780618_2025-04-17_13-48-57_sorted_2025-11-07_16-27-28 ...
Found ephys NWB: /root/capsule/data/ecephys_780618_2025-04-17_13-48-57_sorted_2025-11-07_16-27-28/nwb/ecephys_780618_2025-04-17_13-48-57_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_780618_2025-04-17_13-48-57_sorted_2025-11-07_16-27-28/nwb/ecephys_780618_2025-04-17_13-48-57_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/780618_2025-04-17_13-48-57.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/780618_2025-04-17_13-48-57.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 577
  → Found 577 QC-passed units.

[34/41] Loading session ecephys_781469_2025-03-27_18-45-35_sorted_2025-03-30_16-18-11 ...
Found ephys NWB: /root/capsule/data/ecephys_781469_2025-03-27_18-45-35_sorted_2025-03-30_16-18-11/nwb/ecephys_781469_2025-03-27_18-45-35_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_781469_2025-03-27_18-45-35_sorted_2025-03-30_16-18-11/nwb/ecephys_781469_2025-03-27_18-45-35_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/781469_2025-03-27_18-45-35.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/781469_2025-03-27_18-45-35.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 1285
  → Found 1285 QC-passed units.

[35/41] Loading session ecephys_781469_2025-03-29_10-46-53_sorted_2025-03-30_05-48-42 ...
Found ephys NWB: /root/capsule/data/ecephys_781469_2025-03-29_10-46-53_sorted_2025-03-30_05-48-42/nwb/ecephys_781469_2025-03-29_10-46-53_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_781469_2025-03-29_10-46-53_sorted_2025-03-30_05-48-42/nwb/ecephys_781469_2025-03-29_10-46-53_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/781469_2025-03-29_10-46-53.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/781469_2025-03-29_10-46-53.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 1040
  → Found 1040 QC-passed units.

[36/41] Loading session ecephys_781471_2025-03-27_13-39-06_sorted_2025-03-31_11-52-53 ...
Found ephys NWB: /root/capsule/data/ecephys_781471_2025-03-27_13-39-06_sorted_2025-03-31_11-52-53/nwb/ecephys_781471_2025-03-27_13-39-06_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_781471_2025-03-27_13-39-06_sorted_2025-03-31_11-52-53/nwb/ecephys_781471_2025-03-27_13-39-06_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/781471_2025-03-27_13-39-06.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/781471_2025-03-27_13-39-06.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 677
  → Found 677 QC-passed units.

[37/41] Loading session ecephys_781471_2025-03-28_15-06-14_sorted_2025-03-31_14-10-16 ...
Found ephys NWB: /root/capsule/data/ecephys_781471_2025-03-28_15-06-14_sorted_2025-03-31_14-10-16/nwb/ecephys_781471_2025-03-28_15-06-14_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_781471_2025-03-28_15-06-14_sorted_2025-03-31_14-10-16/nwb/ecephys_781471_2025-03-28_15-06-14_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/781471_2025-03-28_15-06-14.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/781471_2025-03-28_15-06-14.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 1011
  → Found 1011 QC-passed units.

[38/41] Loading session ecephys_781471_2025-03-31_14-33-03_sorted_2025-04-01_15-50-16 ...
Found ephys NWB: /root/capsule/data/ecephys_781471_2025-03-31_14-33-03_sorted_2025-04-01_15-50-16/nwb/ecephys_781471_2025-03-31_14-33-03_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_781471_2025-03-31_14-33-03_sorted_2025-04-01_15-50-16/nwb/ecephys_781471_2025-03-31_14-33-03_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/behavior_nwb/781471_2025-03-31_14-33-03.nwb
Successfully read behavior NWB from: /root/capsule/data/behavior_nwb/781471_2025-03-31_14-33-03.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 1147
  → Found 1147 QC-passed units.

[39/41] Loading session ecephys_795393_2025-09-11_20-05-17_sorted_2025-10-29_15-06-02 ...
Found ephys NWB: /root/capsule/data/ecephys_795393_2025-09-11_20-05-17_sorted_2025-10-29_15-06-02/nwb/ecephys_795393_2025-09-11_20-05-17_experiment1_recording1.nwb
Successfully read ephys NWB from: /root/capsule/data/ecephys_795393_2025-09-11_20-05-17_sorted_2025-10-29_15-06-02/nwb/ecephys_795393_2025-09-11_20-05-17_experiment1_recording1.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/795393_2025-09-11_20-05-17.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/795393_2025-09-11_20-05-17.nwb
Successfully appended units table to behavior NWB.
  → Extracting QC-passed units metadata...
Number of units passing QC: 103
  → Found 103 QC-passed units.

[40/41] Loading session ecephys_795393_2025-09-15_13-05-25_sorted_2025-10-29_20-10-36 ...

,session_id,unit_index,brain_region,ccf_location,device_name,sorted_session_name
0,753124_2024-12-10_17-24-56,9,,"{'best_electrode': 1, 'shank': 0, 'probe': 'Pr...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
1,753124_2024-12-10_17-24-56,14,,"{'best_electrode': 7, 'shank': 0, 'probe': 'Pr...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
2,753124_2024-12-10_17-24-56,17,,"{'best_electrode': 6, 'shank': 0, 'probe': 'Pr...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
3,753124_2024-12-10_17-24-56,20,,"{'best_electrode': 6, 'shank': 0, 'probe': 'Pr...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
4,753124_2024-12-10_17-24-56,26,,"{'best_electrode': 10, 'shank': 0, 'probe': 'P...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
...,...,...,...,...,...,...
24419,795396_2025-09-20_13-11-19,2880,,"{'best_electrode': 22, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
24420,795396_2025-09-20_13-11-19,2887,,"{'best_electrode': 27, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
24421,795396_2025-09-20_13-11-19,2888,,"{'best_electrode': 27, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
24422,795396_2025-09-20_13-11-19,2889,,"{'best_electrode': 27, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
24423,795396_2025-09-20_13-11-19,2892,,"{'best_electrode': 26, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...

In [2]:
metadata=smart_read_csv('/root/capsule/scratch/qc_passed_units_metadata_all_sessions.csv')

In [3]:
metadata

,session_id,unit_index,brain_region,ccf_location,device_name,sorted_session_name
0,753124_2024-12-10_17-24-56,9,NaN,"{'best_electrode': 1, 'shank': 0, 'probe': 'Pr...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
1,753124_2024-12-10_17-24-56,14,NaN,"{'best_electrode': 7, 'shank': 0, 'probe': 'Pr...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
2,753124_2024-12-10_17-24-56,17,NaN,"{'best_electrode': 6, 'shank': 0, 'probe': 'Pr...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
3,753124_2024-12-10_17-24-56,20,NaN,"{'best_electrode': 6, 'shank': 0, 'probe': 'Pr...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
4,753124_2024-12-10_17-24-56,26,NaN,"{'best_electrode': 10, 'shank': 0, 'probe': 'P...",ProbeA,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
...,...,...,...,...,...,...
24419,795396_2025-09-20_13-11-19,2880,NaN,"{'best_electrode': 22, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
24420,795396_2025-09-20_13-11-19,2887,NaN,"{'best_electrode': 27, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
24421,795396_2025-09-20_13-11-19,2888,NaN,"{'best_electrode': 27, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
24422,795396_2025-09-20_13-11-19,2889,NaN,"{'best_electrode': 27, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...
24423,795396_2025-09-20_13-11-19,2892,NaN,"{'best_electrode': 26, 'shank': 3, 'probe': 'P...",ProbeD,ecephys_753124_2024-12-10_17-24-56_sorted_2024...