In [9]:
from nwb_utils import NWBUtils
from optogenetics_utils import create_opto_data_frame, find_unique_combinations,find_unique_stimulation,create_opto_data_frame_combined,load_opto_data_frame,find_unique_values_by_conditions

In [10]:
combined_dataframe=create_opto_data_frame_combined(save_path='/root/capsule/results/combined_opto_data_frame.csv')

Processing NWB files:   0%|          | 0/58 [00:00<?, ?file/s]

Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-04-08_16-06-29.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-04-08_16-06-29.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-04-09_11-05-31.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-04-09_11-05-31.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-04-24_16-15-02.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-04-24_16-15-02.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-05-13_12-51-31.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-05-13_12-51-31.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-05-14_09-51-43.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-05-14_09-51-43.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-06-03_11-03-12.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-06-03_11-03-12.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-06-26_11-01-54.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-06-26_11-01-54.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-07-11_09-08-32.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-07-11_09-08-32.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-07-23_12-07-49.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-07-23_12-07-49.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-07-30_14-17-20.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-07-30_14-17-20.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778149_2025-05-13_10-17-34.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778149_2025-05-13_10-17-34.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778149_2025-05-14_12-21-02.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778149_2025-05-14_12-21-02.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778149_2025-05-15_12-01-40.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778149_2025-05-15_12-01-40.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778149_2025-05-16_15-38-07.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778149_2025-05-16_15-38-07.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778149_2025-07-30_12-53-00.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778149_2025-07-30_12-53-00.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778149_2025-08-05_13-26-31.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778149_2025-08-05_13-26-31.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778149_2025-08-06_11-33-44.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778149_2025-08-06_11-33-44.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/778149_2025-08-07_11-38-01.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778149_2025-08-07_11-38-01.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780289_2025-05-13_11-26-34.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780289_2025-05-13_11-26-34.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780289_2025-05-14_10-56-20.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780289_2025-05-14_10-56-20.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780289_2025-05-15_10-32-25.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780289_2025-05-15_10-32-25.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780289_2025-06-03_15-07-02.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780289_2025-06-03_15-07-02.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780289_2025-06-04_10-40-49.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780289_2025-06-04_10-40-49.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780289_2025-06-06_12-08-29.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780289_2025-06-06_12-08-29.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780289_2025-06-09_12-47-49.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780289_2025-06-09_12-47-49.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780289_2025-08-01_11-12-20.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780289_2025-08-01_11-12-20.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-06-03_11-51-08.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-06-03_11-51-08.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-06-06_14-20-32.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-06-06_14-20-32.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-06-09_14-22-51.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-06-09_14-22-51.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-07-07_15-18-11.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-07-07_15-18-11.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-07-08_13-31-20.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-07-08_13-31-20.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-07-10_10-22-28.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-07-10_10-22-28.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-07-11_13-44-55.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-07-11_13-44-55.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-07-14_14-13-01.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-07-14_14-13-01.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-07-15_10-04-51.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-07-15_10-04-51.nwb
Error processing /root/capsule/data/optogenetics_nwb/780621_2025-07-15_10-04-51.nwb: Latent 'deltaQ' length (516) != number of response trials (0).
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-07-15_10-10-19.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-07-15_10-10-19.nwb
Error processing /root/capsule/data/optogenetics_nwb/780621_2025-07-15_10-10-19.nwb: Latent 'deltaQ' length (516) != number of response trials (0).
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-07-15_10-13-01.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-07-15_10-13-01.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/780621_2025-07-21_13-18-55.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/780621_2025-07-21_13-18-55.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/788198_2025-06-24_12-06-50.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/788198_2025-06-24_12-06-50.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/788198_2025-07-07_13-46-12.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/788198_2025-07-07_13-46-12.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/788198_2025-07-10_08-56-13.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/788198_2025-07-10_08-56-13.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/788198_2025-07-11_10-20-29.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/788198_2025-07-11_10-20-29.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/788198_2025-07-22_13-28-53.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/788198_2025-07-22_13-28-53.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/788198_2025-07-31_12-43-14.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/788198_2025-07-31_12-43-14.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/788198_2025-08-07_14-05-27.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/788198_2025-08-07_14-05-27.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789191_2025-07-22_11-15-16.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789191_2025-07-22_11-15-16.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789191_2025-07-31_14-20-42.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789191_2025-07-31_14-20-42.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789191_2025-08-04_13-46-21.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789191_2025-08-04_13-46-21.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789191_2025-08-06_10-16-29.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789191_2025-08-06_10-16-29.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789191_2025-08-07_10-15-10.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789191_2025-08-07_10-15-10.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789197_2025-07-24_11-54-28.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789197_2025-07-24_11-54-28.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789197_2025-07-28_13-06-48.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789197_2025-07-28_13-06-48.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789197_2025-07-29_12-02-01.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789197_2025-07-29_12-02-01.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789197_2025-07-30_11-23-37.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789197_2025-07-30_11-23-37.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789197_2025-07-31_10-19-05.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789197_2025-07-31_10-19-05.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789197_2025-08-01_09-48-52.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789197_2025-08-01_09-48-52.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789197_2025-08-04_11-26-39.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789197_2025-08-04_11-26-39.nwb
Found behavior NWB: /root/capsule/data/optogenetics_nwb/789197_2025-08-05_10-49-42.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/789197_2025-08-05_10-49-42.nwb
Combined DataFrame saved to /root/capsule/results/combined_opto_data_frame.csv

In [11]:
combined_dataframe_original=combined_dataframe.copy()

In [12]:
combined_dataframe=load_opto_data_frame()

In [13]:
combined_dataframe_original['laser_end']

0          None
1          None
2          None
3          None
4          None
          ...
25885      None
25886      None
25887      None
25888      None
25889    Go cue
Name: laser_end, Length: 25890, dtype: object

In [14]:
combined_dataframe['laser_end']

0          None
1          None
2          None
3          None
4          None
          ...
25885      None
25886      None
25887      None
25888      None
25889    Go cue
Name: laser_end, Length: 25890, dtype: object

In [15]:
find_unique_stimulation(combined_dataframe_original)

,laser_on_trial,laser_wavelength,laser_location,laser_1_power,laser_2_power,laser_on_probability,laser_duration,laser_start,laser_start_offset,laser_end,laser_end_offset,laser_protocol,laser_frequency,laser_rampingdown,laser_pulse_duration,session_wide_control,fraction_of_session,session_start_with,session_alternation,n_trials
0,1,473.0,Both,1.15,1.19,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,197
1,1,473.0,Both,1.15,1.19,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,193
2,1,473.0,Both,1.15,1.19,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,177
3,1,473.0,Both,1.15,1.19,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,172
4,1,473.0,Both,1.34,1.35,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,159
5,1,473.0,Both,1.34,1.35,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,141
6,1,473.0,Both,1.40,1.48,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,133
7,1,473.0,Both,1.40,1.48,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,132
8,1,473.0,Both,1.34,1.35,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,127
9,1,473.0,Both,1.40,1.48,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,110
10,1,473.0,Both,1.40,1.48,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,103
11,1,473.0,Both,1.26,1.21,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,92
12,1,473.0,Both,1.26,1.21,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,88
13,1,473.0,Both,1.40,1.48,0.08,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,83
14,1,473.0,Both,1.40,1.48,0.08,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,81
15,1,473.0,Both,1.40,1.48,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,81
16,1,473.0,Both,1.26,1.21,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,80
17,1,473.0,Both,1.40,1.48,0.08,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,80
18,1,473.0,Both,1.26,1.21,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,75
19,1,473.0,Both,1.12,1.19,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,70
20,1,473.0,Both,1.34,1.35,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,65
21,1,473.0,Both,1.12,1.19,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,63
22,1,473.0,Both,1.12,1.19,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,61
23,1,473.0,Both,1.12,1.19,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,59
24,1,473.0,Both,1.34,1.35,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,1.00,0.002,off,0.5,on,on,52
25,1,473.0,Both,1.40,1.48,0.08,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.02,0.002,off,0.5,on,on,43
26,1,473.0,Both,1.40,1.48,0.08,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.02,0.002,off,0.5,on,on,39
27,1,473.0,Both,1.43,1.40,0.12,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,1.00,0.002,off,0.5,on,on,34
28,1,473.0,Both,1.36,1.40,0.12,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,31
29,1,473.0,Both,1.40,1.48,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.02,0.002,off,0.5,on,on,31
30,1,473.0,Both,1.40,1.48,0.08,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.02,0.002,off,0.5,on,on,29
31,1,473.0,Both,1.43,1.40,0.12,3.0,Go cue,0.0,NA,0.0,Sine,40.0,1.00,0.002,off,0.5,on,on,27
32,1,473.0,Both,1.34,1.35,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,24
33,1,473.0,Both,2.27,2.38,0.08,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,24
34,1,473.0,Both,1.15,1.19,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,21
35,1,473.0,Both,1.15,1.19,0.08,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,20
36,1,473.0,Both,1.20,1.19,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,20
37,1,473.0,Both,1.34,1.35,0.08,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,20
38,1,473.0,Both,1.15,1.19,0.08,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,19
39,1,473.0,Both,2.27,2.38,0.08,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,19
40,1,473.0,Both,1.15,1.19,0.08,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,18
41,1,473.0,Both,1.20,1.19,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,17
42,1,473.0,Both,1.34,1.35,0.08,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,16
43,1,473.0,Both,2.27,2.38,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,16
44,1,473.0,Both,1.34,1.35,0.06,1.5,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,15
45,1,473.0,Both,2.27,2.38,0.08,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,15
46,1,473.0,Both,1.20,1.19,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,14
47,1,473.0,Both,1.20,1.19,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,14
48,1,473.0,Both,1.00,1.35,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,1.00,0.002,off,0.5,on,on,11
49,1,473.0,Both,1.34,0.67,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,11
50,1,473.0,Both,1.36,1.40,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.20,0.002,off,0.5,on,on,7

In [16]:
find_unique_stimulation(combined_dataframe)

,laser_on_trial,laser_wavelength,laser_location,laser_1_power,laser_2_power,laser_on_probability,laser_duration,laser_start,laser_start_offset,laser_end,laser_end_offset,laser_protocol,laser_frequency,laser_rampingdown,laser_pulse_duration,session_wide_control,fraction_of_session,session_start_with,session_alternation,n_trials
0,1,473.0,Both,1.15,1.19,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,197
1,1,473.0,Both,1.15,1.19,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,193
2,1,473.0,Both,1.15,1.19,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,177
3,1,473.0,Both,1.15,1.19,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,172
4,1,473.0,Both,1.34,1.35,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,159
5,1,473.0,Both,1.34,1.35,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,141
6,1,473.0,Both,1.4,1.48,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,133
7,1,473.0,Both,1.4,1.48,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,132
8,1,473.0,Both,1.34,1.35,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,127
9,1,473.0,Both,1.4,1.48,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,110
10,1,473.0,Both,1.4,1.48,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,103
11,1,473.0,Both,1.26,1.21,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,92
12,1,473.0,Both,1.26,1.21,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,88
13,1,473.0,Both,1.4,1.48,0.08,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,83
14,1,473.0,Both,1.4,1.48,0.08,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,81
15,1,473.0,Both,1.4,1.48,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,81
16,1,473.0,Both,1.26,1.21,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,80
17,1,473.0,Both,1.4,1.48,0.08,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,80
18,1,473.0,Both,1.26,1.21,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,75
19,1,473.0,Both,1.12,1.19,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,70
20,1,473.0,Both,1.34,1.35,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,65
21,1,473.0,Both,1.12,1.19,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,63
22,1,473.0,Both,1.12,1.19,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,61
23,1,473.0,Both,1.12,1.19,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,59
24,1,473.0,Both,1.34,1.35,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,1.0,0.002,off,0.5,on,on,52
25,1,473.0,Both,1.4,1.48,0.08,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.02,0.002,off,0.5,on,on,43
26,1,473.0,Both,1.4,1.48,0.08,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.02,0.002,off,0.5,on,on,39
27,1,473.0,Both,1.43,1.4,0.12,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,1.0,0.002,off,0.5,on,on,34
28,1,473.0,Both,1.36,1.4,0.12,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,31
29,1,473.0,Both,1.4,1.48,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.02,0.002,off,0.5,on,on,31
30,1,473.0,Both,1.4,1.48,0.08,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.02,0.002,off,0.5,on,on,29
31,1,473.0,Both,1.43,1.4,0.12,3.0,Go cue,0.0,NA,0.0,Sine,40.0,1.0,0.002,off,0.5,on,on,27
32,1,473.0,Both,1.34,1.35,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,24
33,1,473.0,Both,2.27,2.38,0.08,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,24
34,1,473.0,Both,1.15,1.19,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,21
35,1,473.0,Both,1.15,1.19,0.08,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,20
36,1,473.0,Both,1.2,1.19,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,20
37,1,473.0,Both,1.34,1.35,0.08,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,20
38,1,473.0,Both,1.15,1.19,0.08,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,19
39,1,473.0,Both,2.27,2.38,0.08,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,19
40,1,473.0,Both,1.15,1.19,0.08,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,18
41,1,473.0,Both,1.2,1.19,0.06,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,17
42,1,473.0,Both,1.34,1.35,0.08,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,16
43,1,473.0,Both,2.27,2.38,0.08,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,16
44,1,473.0,Both,1.34,1.35,0.06,1.5,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,15
45,1,473.0,Both,2.27,2.38,0.08,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,15
46,1,473.0,Both,1.2,1.19,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,14
47,1,473.0,Both,1.2,1.19,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,14
48,1,473.0,Both,1.0,1.35,0.06,1.0,Trial start,0.0,NA,0.0,Sine,40.0,1.0,0.002,off,0.5,on,on,11
49,1,473.0,Both,1.34,0.67,0.06,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,11
50,1,473.0,Both,1.36,1.4,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,7

In [23]:
find_unique_stimulation(combined_dataframe,columns=[
        'laser_on_trial', 'laser_wavelength', 'laser_location',   'laser_duration', 'laser_start',
        'laser_start_offset', 'laser_end', 'laser_end_offset', 'laser_protocol',
        'laser_frequency',  'laser_pulse_duration',
        'session_wide_control', 'fraction_of_session', 'session_start_with',
        'session_alternation','laser_1_target_areas','laser_2_target_areas'
    ])

,laser_on_trial,laser_wavelength,laser_location,laser_duration,laser_start,laser_start_offset,laser_end,laser_end_offset,laser_protocol,laser_frequency,laser_pulse_duration,session_wide_control,fraction_of_session,session_start_with,session_alternation,laser_1_target_areas,laser_2_target_areas,n_trials
0,1,473.0,Both,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.002,off,0.5,on,on,left ALM,right ALM,600
1,1,473.0,Both,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.002,off,0.5,on,on,left ALM,right ALM,495
2,1,473.0,Both,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.002,off,0.5,on,on,left ALM,right ALM,452
3,1,473.0,Both,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.002,off,0.5,on,on,left ALM,right ALM,427
4,1,473.0,Both,1.0,Trial start,0.0,NA,0.0,Sine,40.0,0.002,off,0.5,on,on,left MD,right MD,272
5,1,473.0,Both,3.0,Go cue,0.3,NA,0.0,Sine,40.0,0.002,off,0.5,on,on,left MD,right MD,261
6,1,473.0,Both,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.002,off,0.5,on,on,left MD,right MD,234
7,1,473.0,Both,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.002,off,0.5,on,on,left MD,right MD,230
8,1,473.0,Both,3.0,Go cue,0.0,Trial start,0.0,Sine,40.0,0.002,off,0.5,on,on,left ALM,right ALM,123
9,1,473.0,Both,3.0,Go cue,0.3,Trial start,0.0,Sine,40.0,0.002,off,0.5,on,on,left ALM,right ALM,120
10,1,473.0,Both,1.5,Trial start,0.0,NA,0.0,Sine,40.0,0.002,off,0.5,on,on,left ALM,right ALM,15

In [20]:
combined_dataframe.columns

Index(['start_time', 'stop_time', 'animal_response', 'rewarded_historyL',
       'rewarded_historyR', 'delay_start_time', 'goCue_start_time',
       'reward_outcome_time', 'bait_left', 'bait_right',
       ...
       'QLearning_L1F1_CK1_softmax-chosenQ+1',
       'QLearning_L1F1_CK1_softmax-unchosenQ',
       'QLearning_L1F1_CK1_softmax-unchosenQ-1',
       'QLearning_L1F1_CK1_softmax-unchosenQ+1',
       'QLearning_L1F1_CK1_softmax-reward',
       'QLearning_L1F1_CK1_softmax-reward-1',
       'QLearning_L1F1_CK1_softmax-reward+1',
       'QLearning_L1F1_CK1_softmax-choice',
       'QLearning_L1F1_CK1_softmax-choice-1',
       'QLearning_L1F1_CK1_softmax-choice+1'],
      dtype='object', length=122)

In [ ]:
conds = {"laser_start": "Go cue", "laser_end": "Trial start"}
unique_vals = find_unique_values_by_conditions(combined_dataframe, conds, output_column="session")
print(unique_vals)

In [ ]:
nwb_path="/root/capsule/data/optogenetics_nwb/789197_2025-08-05_10-49-42.nwb"

nwb_data=NWBUtils.read_behavior_nwb(nwb_full_path=nwb_path)