In [1]:
from nwb_utils import NWBUtils
from optogenetics_utils import create_opto_data_frame, find_unique_combinations,find_unique_stimulation,create_opto_data_frame_combined,load_opto_data_frame,find_unique_values_by_conditions

In [2]:
combined_dataframe=create_opto_data_frame_combined(sources=['/root/capsule/data/optogenetics_nwb/778147_2025-04-24_16-15-02.nwb'],save_path='/root/capsule/results/combined_opto_data_frame.csv')

Processing NWB files:   0%|          | 0/1 [00:00<?, ?file/s]

Found behavior NWB: /root/capsule/data/optogenetics_nwb/778147_2025-04-24_16-15-02.nwb
Successfully read behavior NWB from: /root/capsule/data/optogenetics_nwb/778147_2025-04-24_16-15-02.nwb
Combined DataFrame saved to /root/capsule/results/combined_opto_data_frame.csv

In [3]:
combined_dataframe_original=combined_dataframe.copy()

In [4]:
combined_dataframe=load_opto_data_frame()

In [5]:
combined_dataframe_original['laser_end']

0        None
1        None
2      Go cue
3        None
4        None
        ...
337      None
338      None
339      None
340      None
341      None
Name: laser_end, Length: 342, dtype: object

In [6]:
combined_dataframe['laser_end']

0        None
1        None
2      Go cue
3        None
4        None
        ...
337      None
338      None
339      None
340      None
341      None
Name: laser_end, Length: 342, dtype: object

In [7]:
find_unique_stimulation(combined_dataframe_original)

,laser_on_trial,laser_wavelength,laser_location,laser_1_power,laser_2_power,laser_on_probability,laser_duration,laser_start,laser_start_offset,laser_end,laser_end_offset,laser_protocol,laser_frequency,laser_rampingdown,laser_pulse_duration,session_wide_control,fraction_of_session,session_start_with,session_alternation,n_trials
0,1,473.0,Both,1.36,1.4,0.12,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,31
1,1,473.0,Both,1.36,1.4,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,7

In [8]:
find_unique_stimulation(combined_dataframe)

,laser_on_trial,laser_wavelength,laser_location,laser_1_power,laser_2_power,laser_on_probability,laser_duration,laser_start,laser_start_offset,laser_end,laser_end_offset,laser_protocol,laser_frequency,laser_rampingdown,laser_pulse_duration,session_wide_control,fraction_of_session,session_start_with,session_alternation,n_trials
0,1,473.0,Both,1.36,1.4,0.12,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,31
1,1,473.0,Both,1.36,1.4,0.06,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.2,0.002,off,0.5,on,on,7

In [4]:
find_unique_stimulation(combined_dataframe,columns=[
        'laser_on_trial', 'laser_wavelength', 'laser_location',   'laser_duration', 'laser_start',
        'laser_start_offset', 'laser_end', 'laser_end_offset', 'laser_protocol',
        'laser_frequency',  'laser_pulse_duration',
        'session_wide_control', 'fraction_of_session', 'session_start_with',
        'session_alternation'
    ])

,laser_on_trial,laser_wavelength,laser_location,laser_duration,laser_start,laser_start_offset,laser_end,laser_end_offset,laser_protocol,laser_frequency,laser_pulse_duration,session_wide_control,fraction_of_session,session_start_with,session_alternation,n_trials
0,1,473.0,Both,50.0,Trial start,0.0,Go cue,0.0,Sine,40.0,0.002,off,0.5,on,on,31
1,1,473.0,Both,3.0,Go cue,0.0,NA,0.0,Sine,40.0,0.002,off,0.5,on,on,7

In [ ]:
conds = {"laser_start": "Go cue", "laser_end": "Trial start"}
unique_vals = find_unique_values_by_conditions(combined_dataframe, conds, output_column="session")
print(unique_vals)

In [ ]:
nwb_path="/root/capsule/data/optogenetics_nwb/789197_2025-08-05_10-49-42.nwb"

nwb_data=NWBUtils.read_behavior_nwb(nwb_full_path=nwb_path)

In [ ]:
data_frame

In [ ]:
find_unique_stimulation(data_frame)

In [ ]:
data_frame.columns

In [ ]:
nwb_data.scratch['metadata']

In [ ]:
nwb_data.session_id